development:
  adapter: postgresql
  encoding: utf8
  database: urlshortnr_development
  pool: 5


test: &TEST
  adapter: postgresql
  encoding: utf8
  database: urlshortnr_test
  pool: 5


production:
  adapter: postgresql
  encoding: utf8
  database: urlshortnr_production
  pool: 5


cucumber:
  <<: *TEST
